# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:12:49+00:00



import argparse
import json
import os
from typing import *
from typing import Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    AcademicCertificateSchema,
    AdcrdCertificatePostRequest,
    AdcrdCertificatePostResponse,
    AdcrdCertificatePostResponse1,
    AdcrdCertificatePostResponse2,
    AdcrdCertificatePostResponse3,
    AdcrdCertificatePostResponse4,
    AdcrdCertificatePostResponse5,
    AdcrdCertificatePostResponse6,
)

app = MCPProxy(
    description='A single consolidated system of MEARK has been integrated with DigiLocker to produce Co-curricular activity Awards for Universities and Academic Institutions of India. Initially starting with all the Universities of Maharashtra.',
    termsOfService='https://apisetu.gov.in/terms.php',
    title='Meark Enterprise Pvt. Ltd.',
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/meark/v3'}],
)


@app.post(
    '/adcrd/certificate',
    description=""" API to verify Admit Card. """,
    tags=['admit_card_management'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def adcrd(body: AdcrdCertificatePostRequest = None):
    """
    Admit Card
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
